spring:
  application:
    name: factory-admin
  profiles:
    active: local
  flyway:
    schemas: public
    outOfOrder: true
    baselineOnMigrate: true
    table: schema_history_admin_service
server:
  port: ${PORT:8086} # Indicate the default PORT where this service will be started
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 10
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
logging:
  level:
    org:
      springframework:
        web: WARN
      hibernate: WARN
    com.sysmex.bcqmun: DEBUG